from __future__ import annotations

import importlib
import pathlib
from typing import Any

from omegaconf import DictConfig, OmegaConf

import fasthep_curator as fc

from .v0 import CuratorConfig, Dataset

DEFAULT_VERSION = 0


def load_config(config_file: str) -> Any:
    """Load a config file and return the structured config."""
    config_path = pathlib.Path(config_file)
    conf = OmegaConf.load(config_path)
    if not isinstance(conf, DictConfig):
        msg = f"Config file {config_file} is not a DictConfig, but {type(conf)}"
        raise TypeError(msg)
    # read version from config
    version = "v" + str(conf.get("version", DEFAULT_VERSION))
    cfg_class = importlib.import_module(f".{version}", __package__).CuratorConfig

    curator = cfg_class.from_dictconfig(conf)
    curator.metadata = {
        "config_file": str(config_path.absolute()),
        "name": config_path.stem,
    }
    return curator


def compact(config: CuratorConfig) -> CuratorConfig:
    """Move values common to all datasets into ``defaults``."""
    if not config.datasets:
        return config

    dataset_dicts = [vars(d) for d in config.datasets]

    common_keys = set(dataset_dicts[0].keys())
    for d in dataset_dicts[1:]:
        common_keys &= set(d.keys())

    defaults: dict[str, Any] = {}
    for key in list(common_keys):
        values = [d[key] for d in dataset_dicts]
        first = values[0]
        if first is not None and all(v == first for v in values):
            defaults[key] = first
            for d in dataset_dicts:
                del d[key]

    if config.defaults:
        config.defaults.update(defaults)
    else:
        config.defaults = defaults
    config.datasets = [Dataset(**d) for d in dataset_dicts]
    return config


def write_config(config: CuratorConfig, config_file: pathlib.Path | str) -> None:
    """Write a config file."""
    with pathlib.Path(config_file).open("w", encoding="utf-8") as f:
        OmegaConf.save(config, f)
        f.write("\n")
        f.write(
            f"# This file was generated by fasthep-curator version {fc.__version__}\n"
        )


__all__ = [
    "CuratorConfig",
    "Dataset",
    "load_config",
]
