from __future__ import annotations

import importlib
import pathlib
from typing import Any

import yaml
from omegaconf import DictConfig, OmegaConf

import fasthep_curator as fc

from .v0 import CuratorConfig, Dataset

DEFAULT_VERSION = 0


def load_config(config_file: str) -> Any:
    """Load a config file and return the structured config."""
    config_path = pathlib.Path(config_file)
    conf = OmegaConf.load(config_path)
    if not isinstance(conf, DictConfig):
        msg = f"Config file {config_file} is not a DictConfig, but {type(conf)}"
        raise TypeError(msg)
    # read version from config
    version = "v" + str(conf.get("version", DEFAULT_VERSION))
    cfg_class = importlib.import_module(f".{version}", __package__).CuratorConfig

    curator = cfg_class.from_dictconfig(conf)
    curator.metadata = {
        "config_file": str(config_path.absolute()),
        "name": config_path.stem,
    }
    return curator


def compact(config: CuratorConfig) -> CuratorConfig:
    """Move values common to all datasets into ``defaults``."""
    if not config.datasets:
        return config
    if len(config.datasets) == 1:
        # If there is only one dataset, no need to compact
        return config

    dataset_dicts = [vars(d) for d in config.datasets]

    ignore_keys = {"name", "files", "nevents", "nfiles"}
    common_keys = set(dataset_dicts[0].keys())
    common_keys -= ignore_keys
    for d in dataset_dicts[1:]:
        common_keys &= set(d.keys())

    defaults: dict[str, Any] = {}
    for key in list(common_keys):
        values = [d[key] for d in dataset_dicts]
        first = values[0]
        if first is not None and all(v == first for v in values):
            defaults[key] = first
            for d in dataset_dicts:
                del d[key]

    if config.defaults:
        config.defaults.update(defaults)
    else:
        config.defaults = defaults
    config.datasets = [Dataset(**d) for d in dataset_dicts]
    return config


# https://stackoverflow.com/questions/25108581/python-yaml-dump-bad-indentation
class CuratorDumper(yaml.Dumper):
    """Custom YAML dumper to avoid using block style for lists."""

    # def increase_indent(self, flow=False, indentless=False):
    #     return super().increase_indent(flow, indentless)
    # disable aliases and anchors, see https://github.com/yaml/pyyaml/issues/103
    def ignore_aliases(self, _: Any) -> bool:
        return True


def _dict_representer(
    dumper: CuratorDumper, data: dict[Any, Any]
) -> yaml.nodes.MappingNode:
    def filter_recursive(value: Any) -> Any:
        """Recursively filter out None, empty lists, and empty dicts."""
        if isinstance(value, dict):
            return {
                k: filter_recursive(v)
                for k, v in value.items()
                if v is not None and v not in ([], {})
            }
        if isinstance(value, list):
            return [
                filter_recursive(v)
                for v in value
                if v is not None and v not in ([], {})
            ]
        return value

    filtered = filter_recursive(data)
    return dumper.represent_mapping("tag:yaml.org,2002:map", filtered)


CuratorDumper.add_representer(dict, _dict_representer)


def write_config(config: CuratorConfig, config_file: pathlib.Path | str) -> None:
    """Write a config file."""
    config = OmegaConf.create(config)  # type: ignore[call-overload]
    cfg = OmegaConf.to_container(config, enum_to_str=True)
    content = yaml.dump(
        cfg,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        Dumper=CuratorDumper,
    )
    with pathlib.Path(config_file).open("w", encoding="utf-8") as f:
        f.write(content)
        f.write("\n")
        f.write(
            f"# This file was generated by fasthep-curator version {fc.__version__}\n"
        )


__all__ = [
    "CuratorConfig",
    "Dataset",
    "load_config",
]
