name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

defaults:
  run:
    shell: bash -exo pipefail {0}

jobs:
  pre-commit:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          create-args: >-
            python=3.12 xrootd pipx uv
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: "all"
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --hook-stage manual --all-files
      - name: Install uv venv
        run: |
          uv venv
          uv pip install "pylint>=3.2" .[test]
        shell: micromamba-shell {0}
      - name: Run PyLint
        run: |
          echo "::add-matcher::$GITHUB_WORKSPACE/.github/matchers/pylint.json"
          uv run pylint fasthep_curator
        shell: micromamba-shell {0}

  checks:
    name: Check Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]
        runs-on: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }} xrootd uv
          init-shell: >-
            bash
          cache-environment: true
          post-cleanup: "all"

      - name: Install package
        run: |
          pip install .[test]
        shell: micromamba-shell {0}

      - name: Test package
        run: >-
          pytest -ra --cov --cov-report=xml --cov-report=term --durations=20
        shell: micromamba-shell {0}

      - name: Upload coverage report
        uses: codecov/codecov-action@v5.4.3
